CREATE TABLE CUSTOMER (
    CUS_CODE INT PRIMARY KEY,
    CUS_LNAME VARCHAR(50),
    CUS_FNAME VARCHAR(50),
    CUS_INITIAL CHAR(1),
    CUS_AREACODE CHAR(3),
    CUS_PHONE VARCHAR(15),
    CUS_BALANCE DECIMAL(10,2)
);

CREATE TABLE INVOICE (
    INV_NUMBER INT PRIMARY KEY,
    INV_DATE DATE,
    CUS_CODE INT
);

CREATE TABLE LINE (
    LINE_NUMBER INT,
    LINE_UNITS INT,
    LINE_PRICE DECIMAL(10,2),
    INV_NUMBER INT,
    P_CODE VARCHAR(20),
    PRIMARY KEY (INV_NUMBER, LINE_NUMBER)
);

CREATE TABLE PRODUCT (
    P_CODE VARCHAR(20) PRIMARY KEY,
    P_DESCRIPT VARCHAR(100),
    P_INDATE DATE,
    P_QOH INT,
    P_MIN INT,
    P_PRICE DECIMAL(10,2),
    P_DISCOUNT DECIMAL(4,2),
    V_CODE INT
);

CREATE TABLE VENDOR (
    V_CODE INT PRIMARY KEY,
    V_NAME VARCHAR(100),
    V_CONTACT VARCHAR(50),
    V_AREACODE CHAR(3),
    V_PHONE VARCHAR(15),
    V_STATE CHAR(2),
    V_ORDER CHAR(1)
);
 
ALTER TABLE INVOICE ADD CONSTRAINT FK_INVOICE_2
    FOREIGN KEY (CUS_CODE)
    REFERENCES CUSTOMER (CUS_CODE);
 
ALTER TABLE LINE ADD CONSTRAINT FK_LINE_2
    FOREIGN KEY (INV_NUMBER)
    REFERENCES INVOICE (INV_NUMBER);
 
ALTER TABLE LINE ADD CONSTRAINT FK_LINE_3
    FOREIGN KEY (P_CODE)
    REFERENCES PRODUCT (P_CODE);
 
ALTER TABLE PRODUCT ADD CONSTRAINT FK_PRODUCT_2
    FOREIGN KEY (V_CODE)
    REFERENCES VENDOR (V_CODE);
